
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import Logo from '../images/loop.svg';


// Menu items
const menuItems = [
  {
    menu: 'About',
    link: '/about',
  },
  {
    menu: 'Product',
    link: '/product',
  },
  {
    menu: 'Services',
    link: '/services',
  },
  {
    menu: 'Contact Us',
    link: '/contact',
  },
];

export default function sidebar() {

const displayMenu = () => {
    return menuItems.map((item) => (
      <Link
        key={item.menu}
        href={item.link}
        className='pb-5 hover:text-yellow md:pb-0 md:pl-6'
      >
        {item.menu}
      </Link>
    ));
  };

  return (
    <>
      <Head>
        <title>Next & Tailwind Sidebar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
                {/* Tailwind CSS classes added to navbar */}
        <div className='flex justify-between p-7 shadow-lg items-center'>
          {/* Logo */}
          <div>
            <Image src={Logo} alt='Logo' width={100} height={100} />
          </div>

        {/* Menu links */}
        <div className='font-inter'>
            <div className='text-red'>
              {displayMenu()}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}